spring:
  # may be overriden in profile files
  # this config should be used in staging/production
  application:
    name: demoapp
  zipkin:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info

server:
  port: 8080

#environment:
  #name: ${ENVIRONMENT}

client:
  issuer_uri: https://oidc.sandbox.bankid.cz/
  client_id: 0c661f12-b6b8-4a15-a343-f19c7ea8ae78
  client_secret: AOGPyjERp-HznpXw9dGlsoJ1JRhW8ysoaoG9dmdPGJ9EffaeIvoty75JqKXSRoz9J3PQV0RPs-ZZ20jjRWUKyK0
  redirect_uri: https://e9af-109-245-115-107.ngrok-free.app/callback
  client_scopes: "openid profile.name profile.email profile.phonenumber"
  plausible:
keystore:
  file:  "classpath:keystore-dev.jks"
  password: change-it

file:
  path: "classpath:demo.sign-m.pdf"

#client:
#  issuer_uri: https://sandbox.dev.bankid.cz/
#  client_id: d85f9986-abd0-4bf7-8790-70e92e247d04
#  client_secret: APSkD9THELxLMMoHXl-omSlhXOdZUOk8Jq2TaTSKcC34RK0Em_FuN8GQkJ1oQb5llRkwo9gYWBVCsNGnsDPb34I
#  redirect_uri: http://localhost:8080/callback
#  client_scopes: "openid profile.name profile.email profile.phonenumber"